#!/bin/bash

set -eu

rm -rf vendor findkit.zip
composer install --no-dev --no-interaction --optimize-autoloader
npm run build
zip -r /tmp/release.zip . -x "node_modules/*" -x ".git/*" -x "tests/*" -x ".wp-env.json"
mv /tmp/release.zip findkit.zip
